# ===============================================
# DESARROLLO - DEV PROFILE
# ===============================================

# Application
cf.server.port=8081

# Database Desarrollo PostgreSQL
cf.spring.datasource.url=jdbc:postgresql://localhost:5432/gestishop
cf.spring.datasource.username=postgres
cf.spring.datasource.password=admin123

# JPA
cf.spring.jpa.show-sql=true

# Archivos / Multipart
cf.media.location=/gestishop/uploads/

# Swagger
cf.springdoc.api-docs.enabled=true
cf.springdoc.swagger-ui.enabled=true