# ===============================================
# PRODUCCION - PROD PROFILE
# ===============================================

# Application
cf.server.port=8090

# Database Produccion PostgreSQL
cf.spring.datasource.url=jdbc:postgresql://TU_IP:PORT/gestishop
cf.spring.datasource.username=postgres
cf.spring.datasource.password=admin123

# JPA
cf.spring.jpa.show-sql=false

# Archivos / Multipart
cf.media.location=/gestishop/uploads/

# Swagger
cf.springdoc.api-docs.enabled=false
cf.springdoc.swagger-ui.enabled=false